/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-10-22 06:59:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.tagplugins.jstl.core.If;
import org.apache.jasper.tagplugins.jstl.core.ForEach;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.If");
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.ForEach");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"de\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"logik.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"style.css\" />\r\n");
      out.write("    <title>Schiffe versenken</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("<!-----------------------------------------------------------Start-------------------------------------------------------------------->\r\n");
      out.write("\t<div id=\"start\" class=\"visible\">\r\n");
      out.write("\t\t<button id=\"bt1\" class=\"btn btn-1 btn-1b\">Spiel starten</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"weiter\" class=\"invisible\">\r\n");
      out.write("\t\t<button id=\"bt2\" class=\"btn btn-1 btn-1b\">Weiter</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!------------------------------------------------------------Konsole---------------------------------------------------------------->\r\n");
      out.write("\t<div id=\"konsole\" class=\"invisible\">\r\n");
      out.write("\t\t<h3>Wähle deine Schiffe</h3>\r\n");
      out.write("\t\t<ul id=\"f\" class=\"flotte\">\r\n");
      out.write("\t\t\t<li id=\"u\">4x U-Boot</li>\r\n");
      out.write("\t\t\t<li id=\"z\">3x Zerstörer</li>\r\n");
      out.write("\t\t\t<li id=\"k\">2x Kreuzer</li>\r\n");
      out.write("\t\t\t<li id=\"s\">1x Schlachtschiff</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul id=\"f2\" class=\"invisible\">\r\n");
      out.write("\t\t\t<li id=\"u\">4x U-Boot</li>\r\n");
      out.write("\t\t\t<li id=\"z\">3x Zerstörer</li>\r\n");
      out.write("\t\t\t<li id=\"k\">2x Kreuzer</li>\r\n");
      out.write("\t\t\t<li id=\"s\">1x Schlachtschiff</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div id=\"rotatediv\" class=\"invisible\">\r\n");
      out.write("\t\t\t<button class=\"listbtn\" id=\"rotate\" >Rotiere Schiffe</button>\r\n");
      out.write("\t\t</div><br>\r\n");
      out.write("\t\t<div id=\"randomdiv\" class=\"visible\">\r\n");
      out.write("\t\t\t<button class=\"listbtn\" id=\"random\" >Züfallig Platzieren</button>\r\n");
      out.write("\t\t</div><br>\r\n");
      out.write("\t\t<div id=\"fertigdiv\" class=\"invisible\">\r\n");
      out.write("\t\t\t<button class=\"listbtn\" id=\"fertig\">Fertig</button>\r\n");
      out.write("\t\t</div><br>\r\n");
      out.write("\t\t<div id=\"fertig2div\" class=\"invisible\">\r\n");
      out.write("\t\t\t<button class=\"listbtn\" id=\"fertig2\">Fertig</button>\r\n");
      out.write("\t\t</div><br>\r\n");
      out.write("\t\t<div id=\"reset\" class=\"visible\">\r\n");
      out.write("    \t\t<button class=\"listbtn\" onClick=\"window.location.reload();\">Neues Spiel</button>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!----------------------------------------------------------Player 1-------------------------------------------------------------------->\r\n");
      out.write("\t<h2 style=\"text-align:center;\"></h2>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"p1\" class=\"invisible\" >\r\n");
      out.write("\t\t<table class=\"grid\">\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t");

				for(int i=0;i<16;i++){
					
      out.write("<col width=\"30\" />\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>&nbsp&nbsp</th>\r\n");
      out.write("\t\t\t\t");

				for(char c='A';c<='P';c++){
					
      out.write("<th>");
      out.print(c);
      out.write("</th>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t");
for(int i=0;i<16;i++){ 
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>");
      out.print(i+1);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t");
for(int j=0;j<16;j++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td id=\"");
      out.print(i);
      out.write('a');
      out.print(j);
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"bclick\" class=\"invisible\" >\r\n");
      out.write("\t\t<table class=\"grid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>&nbsp&nbsp</th>\r\n");
      out.write("\t\t\t\t");

				for(char c='A';c<='P';c++){
					
      out.write("<th class=\"th2\">");
      out.print(c);
      out.write("</th>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
for(int i=0;i<16;i++){ 
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th class=\"th1\">");
      out.print(i+1);
      out.write("</th>\r\n");
      out.write("\t\t\t\t");
for(int j=0;j<16;j++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<td class=\"tdclick\" id=\"");
      out.print(i);
      out.write('c');
      out.print(j);
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
} 
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!----------------------------------------------------------Player 2-------------------------------------------------------------------->\r\n");
      out.write("\t<div id=\"p2\" class=\"invisible\" >\r\n");
      out.write("\t\t\t<table class=\"grid\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t");

					for(int i=0;i<16;i++){
						
      out.write("<col width=\"30\" />\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>&nbsp&nbsp</th>\r\n");
      out.write("\t\t\t\t\t");

					for(char c='A';c<='P';c++){
						
      out.write("<th>");
      out.print(c);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t");
for(int i=0;i<16;i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print(i+1);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t");
for(int j=0;j<16;j++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td id=\"");
      out.print(i);
      out.write('b');
      out.print(j);
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"aclick\" class=\"invisible\" >\r\n");
      out.write("\t\t<table class=\"grid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>&nbsp&nbsp</th>\r\n");
      out.write("\t\t\t\t");

				for(char c='A';c<='P';c++){
					
      out.write("<th class=\"th2\">");
      out.print(c);
      out.write("</th>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
for(int i=0;i<16;i++){ 
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th class=\"th1\">");
      out.print(i+1);
      out.write("</th>\r\n");
      out.write("\t\t\t\t");
for(int j=0;j<16;j++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<td class=\"tdclick\" id=\"");
      out.print(i);
      out.write('d');
      out.print(j);
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
} 
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
